version: '3.3'

services:
  grafana:
    image: grafana/grafana-oss:8.3.3-ubuntu
    container_name: grafana
    ports:
      - 3000:3000
    links:
      - postgres
    volumes:
      - './data/grafana:/var/lib/grafana'
  postgres:
    image: postgres:14.1-bullseye
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - './data/pg:/var/lib/postgresql/data'
  adminer:
    image: adminer
    restart: always
    links:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - 3001:8080
  spacyapi:
    # git clone git@github.com:fpompermaier/spacy-api-docker.git && cd spacy-api-docker
    # docker build -t spacy-api-docker:base .
    # # replace the base in docker/de/Dockerfile with spacy-api-docker:base
    # docker build -t spacy-api-docker:de -f docker/de/Dockerfile .

    #image: spacy-api-docker:de
    image: bbieniek/spacyapi:de_v3
    ports:
      - '46464:80'
    restart: always
